title: SCCA Landing Zone Workload Expansion
description: SCCA Secure Landing Zone Workload Expansion developed by OCI
schemaVersion: 1.1.0
version: "1.1.0"
locale: en
variableGroups:
  - title: Provider Variables
    visible: false
    variables:
      - api_fingerprint
      - api_private_key_path
      - region
      - tenancy_ocid
      - current_user_ocid
  - title: Compartment Variables
    visible: true
    variables:
      - mission_owner_key
      - enable_compartment_delete
      - workload_compartment_name
      - vdms_compartment_name
      - home_compartment_id
  - title: Network Variables
    visible: true
    variables:
      - workload_vcn_cidr_block
      - workload_vcn_dns_label
      - workload_subnet_cidr
      - workload_subnet_dns_label
      - workload_db_vcn_cidr_block
      - workload_db_dns_label
      - workload_db_subnet_cidr_block
      - workload_db_subnet_dns_label
      - vdss_vcn_cidr_block
      - vdms_vcn_cidr_block
      - enable_workload_load_balancer
      - enable_workload_vtap
      - drg_id
  - title: Identity Variables
    visible: true
    variables:
      - mission_owner_workload_admin_group
      - identity_domain_name
      - idcs_endpoint
      - master_encryption_key_ocid
  - title: Monitoring Variables
    visible: true
    variables:
      - workload_warning_topic_endpoints
      - workload_critical_topic_endpoints
  - title: Invisible Variables
    visible: false
    variables:
      -  is_workload_vtap_enabled
      - enable_workload_critical_alarm
      - enable_workload_warning_alarm

variables:
  api_fingerprint:
    type: string
    description: The fingerprint of API
    default: "Value not required in Oracle Resource Manager."
    title: Api Fingerprint
  api_private_key_path:
    type: string
    description: The local path to the API private key
    default: "Value not required in Oracle Resource Manager."
    title: Api Private Key Path
  region:
    type: string
    description: the OCI region LZ is deployed to.
    title: Region
    required: true
  tenancy_ocid:
    type: string
    description: The OCID of tenancy
    title: Tenancy OCID
  current_user_ocid:
    type: string
    description: OCID of the current user
    title: Current User OCID
  mission_owner_key:
    type: string
    description: "The unique label used to avoid naming conflicts"
    title: Mission Owner Key
    required: true
  workload_compartment_name:
    type: string
    description: "Name of the SCCA Landing Zone Workload compartment."
    title: Workload Compartment Name
    required: true
  home_compartment_id:
    type: oci:identity:compartment:id
    description: "The OCID of SCCA Landing Zone Home compartment"
    title: Home Compartment OCID
    required: true
  enable_compartment_delete:
    type: boolean
    description: "Set to true to allow the compartments to delete on terraform destroy."
    title: Enable Compartment Delete
    default: true
    required: true
  mission_owner_workload_admin_group:
    type: string
    decription: "Name of the Mission Owner Workload Admin user group"
    title: Mission Owner Workload Admin Group Name
    required: true
  idcs_endpoint:
    type: string
    description: "URL endpoint of the existing identity domain"
    title: IDCS Endpoint
    required: true
  identity_domain_name:
    type: string
    description: "Identity domain display name"
    title: Identity Domain Display Name
    required: true
  master_encryption_key_ocid:
    type: string
    description: "OCID of the master encryption key"
    title: Master Encryption Key OCID
    required: true
  vdms_compartment_name:
    type: string
    description: "Full name of the VDMS compartment, including region key"
    title: VDMS Compartment Name
    required: true
  workload_warning_topic_endpoints:
    type: array
    items:
      type: string
      pattern: ^[^\s@]+@([^\s@.,]+\.)+[^\s@.,]{2,}$
    description: "List of email addresses for Workload Warning notifications."
    title: Workload Warning Topic Endpoints
  workload_critical_topic_endpoints:
    type: array
    items:
      type: string
      pattern: ^[^\s@]+@([^\s@.,]+\.)+[^\s@.,]{2,}$
    description: "List of email addresses for Workload Critical notifications."
    title: Workload Critical Topic Endpoints
  workload_vcn_cidr_block:
    type: string
    decription: "Workload VCN CIDR Block"
    title: Workload VCN CIDR Block
    required: true
  workload_vcn_dns_label:
    type: string
    description: "Workload VCN DNS Label"
    title: Workload VCN DNS Label
    required: true
  workload_subnet_cidr:
    type: string
    description: "Workload Subnet CIDR Block"
    title: Workload Subnet CIDR Block
    required: true
  workload_subnet_dns_label:
    type: string
    description: "Workload Subnet DNS Label"
    title: Workload Subnet DNS Label
    required: true
  workload_db_vcn_cidr_block:
    type: string
    description: "Workload DB VCN CIDR Block"
    title: Workload DB VCN CIDR Block
    required: true
  workload_db_dns_label:
    type: string
    description: "Workload Database DNS Label"
    title: Workload Database DNS Label
    required: true
  workload_db_subnet_cidr_block:
    type: string
    description: "Workload DB subnet CIDR Block"
    title: Workload DB subnet CIDR Block
    required: true
  workload_db_subnet_dns_label:
    type: string
    description: "Workload Database Subnet DNS Label"
    title: Workload Database Subnet DNS Label
    required: true
  drg_id:
    type: string
    description: "the OCID of DRG from the base stack"
    title: DRG OCID
    required: true
  vdss_vcn_cidr_block:
    type: string
    description: "VDSS VCN CIDR Block"
    title: VDSS VCN CIDR Block
    required: true
  vdms_vcn_cidr_block:
    type: string
    description: "VDMS VCN CIDR Block"
    title: VDMS VCN CIDR Block
    required: true
  enable_workload_load_balancer:
    type: boolean
    description: "Enable Workload Load Balancer"
    title: Enable Workload Load Balancer
    required: true
  enable_workload_vtap:
    type: boolean
    description: "Enable Workload VTAP"
    title: Enable Workload VTAP
    required: true
